<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!-- HTML Meta Tags -->
    <title><?=$pageMeta->Title ?? "Ben Yafai"?></title>
    <meta name="description" content="Links to my social profiles and other stuff">
    
    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://ben.yaf.ai">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Ben Yafai">
    <meta property="og:description" content="Links to my social profiles and other stuff">
    <meta property="og:image" content="https://ben.yaf.ai/styles/og-header.png">
    
    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="ben.yaf.ai">
    <meta property="twitter:url" content="https://ben.yaf.ai">
    <meta name="twitter:title" content="Ben Yafai">
    <meta name="twitter:description" content="Links to my social profiles and other stuff">
    <meta name="twitter:image" content="https://ben.yaf.ai/styles/og-header.png">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/styles/style.css">
    <link rel="stylesheet" href="/styles/fun.css">
    <link rel="stylesheet" href="/styles/dark.min.css" media="(prefers-color-scheme: dark)">
    <link rel="stylesheet" href="/styles/default.min.css" media="(prefers-color-scheme: light)">
    <link rel="icon" type="image/x-icon" href="/styles/favicon.ico">
    <style>
        :root {
            --bg: #f5f5f5;
            --fg: #0d5291;
            --ac: #9ACD32;
            --code-bg: #22212c;
            --code-fg: #f5f5f5;
            --me-background: var(--ac);
            --me-arm: #0d5291;
            --me-body: #1e90ff;
            --me-hair: #141312;
            --me-skin: #f7cba9;
            --me-skinshade: #e8a679;
            --me-eyes: #39395c;
        }
        
        @media (prefers-color-scheme: dark) {
            :root {
                --bg: #0d5291;
                --fg: #f5f5f5;
            }
        }
    </style>
    <style id="cssChange">
    </style>
    <script type="text/javascript" src="/js/colors.js" async></script>
    <script type="text/javascript" src="/js/share.js" async></script>
    <script type="text/javascript" src="/js/highlight.min.js"></script>
    <script>hljs.highlightAll();</script>
    <script async src="https://who.tunnel.li/script.js" data-website-id="0bca39b8-5af3-4657-87f3-20e437fbe466"></script>
</head>

<body>
    <main>
        <header>
            <div class="avatar">
                <?=file_get_contents(__DIR__ . "/../svg/ben.svg")?>
            </div>
            <div class="head">
                <?php if ($four0four) : ?>
                    <h1 id="name">Ben Who?</h1>
                <?php else : ?>
                    <h1 id="name">Ben Yafai</h1>
                <?php endif; ?>
                <ul>
                    <li><?=file_get_contents(__DIR__ . "/../svg/link.svg")?><a href="https://ben.yaf.ai">ben.yaf.ai</a></li>
                    <li><?=file_get_contents(__DIR__ . "/../svg/envelope.svg")?><a href="mailto:ben@yaf.ai">ben@yaf.ai</a></li>
                </ul>
            </div>
            <input type="range" min="1" max="5" step="1" value="1" id="colorWay" oninput="colorway(this.value)" onchange="colorway(this.value)" />
            <label for="colorWay">Slide to change colour!</label>
            </header>
        <div id="content">
            <?=$content?>
        </div>
    </main>
</body>
</html>

